const $ = (s, root=document) => root.querySelector(s);
const app = $('#app');
const wordsLab = [
  ['phone',0],['owl',1],['photo',2],['cow',3],['cloud',4],['house',5],['ring',6],['king',7]
];
const unoWords = ['dolphin','phone','photo','alphabet','phin','phil','elephant','house','loud','sound','mouse','around','round','allow','crown','clown','cow','owl'];
const bowlWords = [
  ['phone',1],['photo',1],['owl',1],['cow',1],['cloud',2],['house',2],['mouse',2],['sound',2],['dolphin',3],['around',3],['elephant',4],['proud',4],['crowd',4],['count',5],['loud',5]
];
const state={sound:true,screen:'home',lab:null,uno:null,bowl:null};
const shuffle=a=>[...a].sort(()=>Math.random()-.5);
function saveStars(n){const v=+localStorage.getItem('forestStars')||0;localStorage.setItem('forestStars',v+n)}
function toast(t){const el=document.createElement('div');el.className='toast';el.textContent=t;document.body.append(el);setTimeout(()=>el.remove(),2100)}
function speak(word){if(!state.sound)return; speechSynthesis.cancel(); const u=new SpeechSynthesisUtterance(word);u.lang='en-US';u.rate=.75;speechSynthesis.speak(u)}
function shell(content,active=''){return `<div class="app"><header class="topbar"><div class="brand"><span class="brand-leaves">🌿</span><span class="brand-text">Forest Friends<small>LEARNING CLUB</small></span></div></header>${content}</div>`}
function go(screen){state.screen=screen;if(screen==='lab')initLab();if(screen==='uno')initUno();if(screen==='bowling')initBowling();render()}
function toggleSound(){state.sound=!state.sound;render()}
function render(){if(state.screen==='home')renderHome();if(state.screen==='lab')renderLab();if(state.screen==='uno')renderUno();if(state.screen==='bowling')renderBowling()}
function renderHome(){app.innerHTML=shell(`<main class="screen home-screen"><img class="scene-bg" src="assets/home-3d.png?v=20260809-10" alt="Fox and Owl magical forest game room"><div class="portal-badges" aria-hidden="true"><img class="portal-badge lab-badge" src="assets/icon-lab-3d.png?v=12"><img class="portal-badge uno-badge" src="assets/icon-uno-3d.png?v=12"><img class="portal-badge bowling-badge" src="assets/icon-bowling-3d.png?v=12"></div><div class="title-plaque"><h1 class="hero-title">Choose Your<br><span>Adventure</span></h1></div><section class="game-grid">
${homeCard('lab','🧪',"The Owl’s Laboratory",'Match each English word to the right picture and brew a magic potion.','#13a980','#9af3dc55','🦉🔬','Play')}
${homeCard('uno','🃏','Word Uno: Fox vs Owl','Match a color, symbol, or sound pattern. Read every word aloud!','#e27019','#ffd77c55','🦊🦉','Start')}
${homeCard('bowling','🎳','Forest Bowling','Choose a mystery ball, read the word, and roll for your team.','#278dcc','#73c9ff55','🦊🎳🦉','Play')}
</section></main>${adventureInfo()}`,'home');if(location.hash==='#adventures')requestAnimationFrame(()=>document.getElementById('adventures')?.scrollIntoView())}
function adventureInfo(){return `<section class="adventures-info" id="adventures"><div class="info-heading"><span>✦</span><div><p>EXPLORE THE GAMES</p><h2>Meet the Adventures</h2></div><span>✦</span></div><div class="info-grid"><article class="info-card lab-info"><div class="info-icon"><img src="assets/icon-lab-3d.png?v=11" alt="Magical potion flask"></div><div><small>WORD & PICTURE GAME</small><h3>The Owl’s Laboratory</h3><p>Read each English word and choose the matching picture. Every correct answer fills a flask and helps Owl brew a magical potion!</p></div><button onclick="go('lab')">Enter the Lab →</button></article><article class="info-card uno-info"><div class="info-icon"><img src="assets/icon-uno-3d.png?v=11" alt="Colorful OWL word cards"></div><div><small>TWO-PLAYER CARD GAME</small><h3>Word Uno: Fox vs Owl</h3><p>Match cards by color, symbol, or sound pattern. Read every word aloud and use special cards to become the forest champion.</p></div><button onclick="go('uno')">Play Word Uno →</button></article><article class="info-card bowl-info"><div class="info-icon"><img src="assets/icon-bowling-3d.png?v=11" alt="Bowling ball and pins"></div><div><small>TEAM READING CHALLENGE</small><h3>Forest Bowling</h3><p>Choose a mystery ball, read the hidden word, and roll for your team. Score points, discover special balls, and win the golden trophy!</p></div><button onclick="go('bowling')">Go Bowling →</button></article></div></section>`}
function homeCard(id,icon,title,desc,accent,glow,chars,action){return `<article class="game-card" style="--accent:${accent};--glow:${glow}"><div class="game-icon">${icon}</div><h2>${title}</h2><p>${desc}</p><div class="characters">${chars}</div><button class="play-btn" onclick="go('${id}')">${title}</button></article>`}
function gameHead(title,badge){return `<div class="game-header"><button class="back-btn" onclick="go('home')">← Games</button><h1>${title}</h1><div class="badge">${badge}</div></div>`}
const labReadingWords=['dolphin','phone','photo','alphabet','phin','phil','elephant'];
const labColors=['#8c3ee8','#28a9f2','#63bf3d'];
let labTimer=null,labAudio=null,labMusicTimer=null;
let lastLabWord='',lastLabLayout='';
function labKey(tubes){return tubes.map(t=>t.join('')).join('|')}
function labGoal(tubes){return tubes.filter(t=>t.length).every(t=>t.length===4&&t.every(c=>c===t[0]))}
function labSolve(tubes){const start=tubes.map(t=>[...t]),queue=[[start,[]]],seen=new Set([labKey(start)]);for(let qi=0;qi<queue.length&&qi<50000;qi++){const [now,path]=queue[qi];if(labGoal(now))return path;for(let a=0;a<4;a++)for(let b=0;b<4;b++){if(a===b||!now[a].length||now[b].length===4||now[b].length&&now[b].at(-1)!==now[a].at(-1))continue;const next=now.map(t=>[...t]);next[b].push(next[a].pop());const key=labKey(next);if(!seen.has(key)){seen.add(key);queue.push([next,[...path,[a,b]]])}}}return null}
function makeLabPuzzle(){for(let tries=0;tries<180;tries++){const pieces=shuffle([0,0,0,0,1,1,1,1,2,2,2,2]),filled=[pieces.slice(0,4),pieces.slice(4,8),pieces.slice(8,12)],tubes=shuffle([...filled,[]]),key=labKey(tubes),solution=labSolve(tubes);if(key!==lastLabLayout&&solution&&solution.length>=7&&solution.length<=16&&!filled.some(t=>t.every(c=>c===t[0]))){lastLabLayout=key;return tubes}}const fallback=shuffle([[[0,0,1,1],[1,1,2,2],[2,2,0,0],[]],[[0,1,0,1],[1,2,1,2],[2,0,2,0],[]]]);for(const tubes of fallback){const mixed=shuffle(tubes.map(t=>[...t]));if(labSolve(mixed)){lastLabLayout=labKey(mixed);return mixed}}return [[0,0,1,1],[1,1,2,2],[2,2,0,0],[]]}
function nextLabWord(){const choices=labReadingWords.filter(w=>w!==lastLabWord);lastLabWord=choices[Math.floor(Math.random()*choices.length)];return lastLabWord}
function initLab(){state.lab={tubes:makeLabPuzzle(),selected:null,pending:null,word:'',moves:0,history:[],hintsUsed:0,hintPair:null,hintShowing:false,startedAt:Date.now(),elapsed:0,tutorial:true,won:false,pouring:null};clearInterval(labTimer);labTimer=setInterval(updateLabClock,1000)}
function updateLabClock(){const l=state.lab;if(!l||l.won)return;l.elapsed=Math.floor((Date.now()-l.startedAt)/1000);const e=$('#labTime');if(e)e.textContent=formatTime(l.elapsed)}
function formatTime(s){return `${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}
function validLabMove(from,to){const a=state.lab.tubes[from],b=state.lab.tubes[to];return from!==to&&a.length&&b.length<4&&(!b.length||b.at(-1)===a.at(-1))}
function safeLabMove(from,to){if(!validLabMove(from,to))return false;const next=state.lab.tubes.map(t=>[...t]);next[to].push(next[from].pop());return labGoal(next)||Boolean(labSolve(next))}
function labAmount(){return 1}
function labFlaskTap(i){const l=state.lab;if(l.pending||l.pouring||l.won||l.hintShowing)return;if(l.selected===null){if(!l.tubes[i].length)return labShake(i);l.selected=i;l.hintPair=null;playLabTone(420,.08);return renderLab()}if(l.selected===i){l.selected=null;return renderLab()}const from=l.selected;if(!safeLabMove(from,i)){l.selected=l.tubes[i].length?i:from;l.hintPair=null;renderLab();return setTimeout(()=>labShake(i),20)}l.selected=null;l.pending={from,to:i};l.word=nextLabWord();playLabTone(650,.12);renderLab()}
function labShake(i){document.querySelector(`[data-flask="${i}"]`)?.classList.add('invalid');setTimeout(()=>document.querySelector(`[data-flask="${i}"]`)?.classList.remove('invalid'),450)}
function confirmLabWord(){const l=state.lab;if(!l.pending)return;const {from,to}=l.pending,amount=labAmount(from,to);l.history.push(l.tubes.map(t=>[...t]));l.pouring={from,to};l.pending=null;l.moves++;renderLab();setTimeout(()=>{for(let n=0;n<amount;n++)l.tubes[to].push(l.tubes[from].pop());l.pouring=null;playLabTone(760,.18);l.won=labSolved();if(l.won){l.elapsed=Math.floor((Date.now()-l.startedAt)/1000);clearInterval(labTimer);saveStars(10);playLabWin()}renderLab()},650)}
function labSolved(){return state.lab.tubes.filter(t=>t.length).every(t=>t.length===4&&t.every(c=>c===t[0]))}
function undoLab(){const l=state.lab;if(!l.history.length||l.pouring)return;l.tubes=l.history.pop();l.moves=Math.max(0,l.moves-1);l.selected=null;l.hintPair=null;renderLab()}
function restartLab(){initLab();state.lab.tutorial=false;renderLab()}
function hintLab(){const l=state.lab;if(l.hintsUsed>=3||l.pending||l.pouring||l.hintShowing)return;const move=labSolve(l.tubes)?.[0];if(move){l.selected=null;l.hintPair=move;l.hintShowing=true;l.hintsUsed++;renderLab();setTimeout(()=>{if(state.lab!==l)return;l.hintPair=null;l.hintShowing=false;renderLab()},2000)}}
function closeLabTutorial(){state.lab.tutorial=false;state.lab.startedAt=Date.now();playLabTone(520,.12);startLabMusic();renderLab()}
function startLabMusic(){clearInterval(labMusicTimer);if(!state.sound)return;const notes=[220,262,294,262];let i=0;labMusicTimer=setInterval(()=>{if((state.screen==='lab'||state.screen==='uno')&&state.sound)playLabTone(notes[i++%notes.length],1.8)},4200)}
function playLabTone(freq,d=.1){if(!state.sound)return;try{labAudio=labAudio||new AudioContext();const o=labAudio.createOscillator(),g=labAudio.createGain();o.frequency.value=freq;o.type='sine';g.gain.setValueAtTime(.07,labAudio.currentTime);g.gain.exponentialRampToValueAtTime(.001,labAudio.currentTime+d);o.connect(g).connect(labAudio.destination);o.start();o.stop(labAudio.currentTime+d)}catch{}}
function playLabWin(){[523,659,784,1046].forEach((n,i)=>setTimeout(()=>playLabTone(n,.35),i*160))}
function labTubeHtml(t,i){const l=state.lab,hintFrom=l.hintPair?.[0]===i;return `<button class="sort-flask ${l.selected===i?'selected':''} ${hintFrom?'hint-from':''} ${l.pouring?.from===i?'pouring':''}" data-flask="${i}" onclick="labFlaskTap(${i})" aria-label="Flask ${i+1}"><span class="flask-neck"></span><span class="liquid-stack">${t.map((c,j)=>`<i style="--c:${labColors[c]};--layer:${j}"></i>`).join('')}</span><span class="flask-number">${i+1}</span></button>`}
function tutorialLabFlask(colors){return `<span class="sort-flask tutorial-sort-flask"><span class="flask-neck"></span><span class="liquid-stack">${colors.map((c,j)=>`<i style="--c:${labColors[c]};--layer:${j}"></i>`).join('')}</span></span>`}
function renderLab(){const l=state.lab;const game=l.won?`<div class="water-win"><div class="win-potion"></div><h2>You Win!</h2><h3>Great job!</h3><p>Moves: <b>${l.moves}</b> &nbsp; Time: <b>${formatTime(l.elapsed)}</b></p><button onclick="restartLab()">Play Again</button></div>`:`<div class="water-game"><p class="sort-goal">Sort the potions by color!</p><div class="sort-flasks">${l.tubes.map(labTubeHtml).join('')}</div><p class="sort-help">${l.hintShowing?'Watch the glowing flask…':'Tap a flask, then tap another flask.'}</p></div>`;const reading=l.pending?`<div class="reading-overlay"><div class="reading-card"><small>READ THE MAGIC WORD</small><strong>${l.word}</strong><button onclick="confirmLabWord()">OK</button></div></div>`:'';const tutorial=l.tutorial?`<div class="lab-tutorial"><div><h2>Sort the colors!</h2><div class="tutorial-flasks">${tutorialLabFlask([1,2,0,1])}<b>→</b>${tutorialLabFlask([0,2,1,0])}</div><p>Tap a flask, then tap another flask.</p><p>Read the word and tap <b>OK</b> to pour.</p><button onclick="closeLabTutorial()">Let’s Play!</button></div></div>`:'';app.innerHTML=shell(`<main class="lab-game-screen water-sort-screen"><img class="lab-room-bg" src="assets/lab-room-3d.png?v=20260809-14" alt="Cozy magical owl laboratory"><button class="lab-back" onclick="go('home')">← Games</button><h1 class="lab-title">The Owl’s Laboratory</h1><div class="lab-hud"><span>Moves <b>${l.moves}</b></span><span>Time <b id="labTime">${formatTime(l.elapsed)}</b></span><span>Hints <b>${l.hintsUsed}/3</b></span></div><section class="lab-board-ui water-board">${game}</section><nav class="lab-controls"><button onclick="undoLab()" ${!l.history.length||l.hintShowing?'disabled':''}>↶ <span>Undo</span></button><button onclick="restartLab()">↻ <span>Restart</span></button><button onclick="hintLab()" ${l.hintsUsed>=3||l.hintShowing?'disabled':''}>? <span>Hint</span></button></nav>${reading}${tutorial}</main>`,'games')}
const colors=['#c83d2f','#32894a','#2385bd','#dc9721'];
const unoSpecials=[['Skip','⊘'],['Reverse','↔'],['Draw 2','+2'],['Wild','★'],['Wild Draw 4','+4']];
let unoTimer=null,unoActionTimer=null,unoId=0;
function makeUnoCard(word,color,special=null,symbol=''){return{id:++unoId,word,color,special,symbol}}
function makeUnoDeck(){const deck=[];for(let copy=0;copy<2;copy++)unoWords.forEach((word,i)=>deck.push(makeUnoCard(word,colors[(i+copy)%4])));for(let c=0;c<4;c++){deck.push(makeUnoCard('',colors[c],'Skip','⊘'),makeUnoCard('',colors[c],'Reverse','↔'),makeUnoCard('',colors[c],'Draw 2','+2'))}for(let i=0;i<3;i++)deck.push(makeUnoCard('',null,'Wild','★'),makeUnoCard('',null,'Wild Draw 4','+4'));return shuffle(deck)}
function initUno(){clearTimeout(unoActionTimer);clearInterval(unoTimer);const deck=makeUnoDeck(),fox=deck.splice(0,7),owl=deck.splice(0,7);let first=deck.shift();while(first.special){deck.push(first);first=deck.shift()}state.uno={players:[{name:'Fox',hand:fox},{name:'Owl',hand:owl}],deck,discard:[first],activeColor:first.color,turn:0,pending:null,colorChoice:null,panel:'rules',winner:null,startedAt:Date.now(),elapsed:0,played:0,unoWindow:false,unoOwner:null,drawnOnly:null,reaction:'Fox goes first!'};unoTimer=setInterval(updateUnoClock,1000);startLabMusic();render()}
function updateUnoClock(){const u=state.uno;if(!u||u.winner!==null)return;u.elapsed=Math.floor((Date.now()-u.startedAt)/1000);const el=$('#unoTime');if(el)el.textContent=formatTime(u.elapsed)}
function refillUnoDeck(){const u=state.uno;if(u.deck.length)return;const top=u.discard.pop();u.deck=shuffle(u.discard);u.discard=[top]}
function drawUnoCards(pi,count){const u=state.uno;for(let i=0;i<count;i++){refillUnoDeck();if(u.deck.length)u.players[pi].hand.push(u.deck.pop())}}
function unoPlayable(card){const u=state.uno,top=u.discard.at(-1);return !card.color||card.color===u.activeColor||card.word&&card.word===top.word}
function chooseUnoCard(pi,i){const u=state.uno;if(u.turn!==pi||u.pending||u.colorChoice||u.unoWindow)return;const card=u.players[pi].hand[i];if(u.drawnOnly!==null&&i!==u.drawnOnly)return;if(!unoPlayable(card))return unoNudge(pi,i);if(card.word){u.pending={pi,index:i,card};u.reaction=`${u.players[pi].name}, read the word aloud.`;playLabTone(640,.12);render()}else if(!card.color){u.colorChoice={pi,index:i,card};render()}else playUnoCard(pi,i,card.color)}
function confirmUnoWord(){const u=state.uno;if(!u.pending)return;const {pi,index,card}=u.pending;u.pending=null;if(!card.color){u.colorChoice={pi,index,card};render()}else playUnoCard(pi,index,card.color)}
function chooseWildColor(color){const u=state.uno;if(!u.colorChoice)return;const {pi,index}=u.colorChoice;u.colorChoice=null;playUnoCard(pi,index,color)}
function playUnoCard(pi,index,chosenColor){const u=state.uno,card=u.players[pi].hand.splice(index,1)[0];u.discard.push(card);u.activeColor=card.color||chosenColor;u.played++;u.drawnOnly=null;playLabTone(card.special?880:720,.16);u.reaction=`${u.players[pi].name} played a card!`;if(!u.players[pi].hand.length)return finishUno(pi);const opponent=1-pi;let sameTurn=false;if(card.special==='Skip'||card.special==='Reverse')sameTurn=true;if(card.special==='Draw 2'){drawUnoCards(opponent,2);sameTurn=true}if(card.special==='Wild Draw 4'){drawUnoCards(opponent,4);sameTurn=true}if(u.players[pi].hand.length===1&&!u.unoWindow){u.unoWindow=true;u.unoOwner=pi;u.afterUnoTurn=sameTurn?pi:opponent;u.turn=pi;render();unoActionTimer=setTimeout(()=>{if(!state.uno?.unoWindow)return;drawUnoCards(state.uno.unoOwner,2);state.uno.unoWindow=false;state.uno.reaction='UNO missed — draw two!';state.uno.turn=state.uno.afterUnoTurn;render()},2400);return}u.turn=sameTurn?pi:opponent;render()}
function pressUno(){const u=state.uno;if(!u.unoWindow)return;clearTimeout(unoActionTimer);u.unoWindow=false;u.reaction=`${u.players[u.unoOwner].name} says UNO!`;playLabTone(1040,.3);u.turn=u.afterUnoTurn;render()}
function unoDraw(){const u=state.uno,pi=u.turn;if(u.pending||u.colorChoice||u.unoWindow||u.players[pi].hand.some(unoPlayable))return;drawUnoCards(pi,1);const i=u.players[pi].hand.length-1;u.reaction=`${u.players[pi].name} drew a card.`;playLabTone(420,.1);if(unoPlayable(u.players[pi].hand[i])){u.drawnOnly=i;render()}else{u.turn=1-pi;render()}}
function scheduleFox(){clearTimeout(unoActionTimer);unoActionTimer=setTimeout(foxTurn,900)}
function foxTurn(){const u=state.uno;if(!u||u.winner!==null||u.turn!==0)return;let options=u.players[0].hand.map((c,i)=>[c,i]).filter(([c])=>unoPlayable(c));if(!options.length){drawUnoCards(0,1);const i=u.players[0].hand.length-1;if(unoPlayable(u.players[0].hand[i]))options=[[u.players[0].hand[i],i]];else{u.turn=1;u.reaction='Fox drew a card. Your turn!';return render()}}const [card,index]=options[Math.floor(Math.random()*options.length)],chosen=card.color||colors[Math.floor(Math.random()*4)];playUnoCard(0,index,chosen)}
function finishUno(pi){const u=state.uno;u.winner=pi;u.elapsed=Math.floor((Date.now()-u.startedAt)/1000);clearInterval(unoTimer);clearTimeout(unoActionTimer);saveStars(12);playLabWin();render()}
function unoNudge(pi,i){document.querySelector(`[data-owner="${pi}"][data-uno-card="${i}"]`)?.classList.add('uno-wrong');setTimeout(()=>document.querySelector(`[data-owner="${pi}"][data-uno-card="${i}"]`)?.classList.remove('uno-wrong'),400)}
function unoDigraph(word){word=word.toLowerCase();if(word.includes('ph'))return'ph';if(word.includes('ou'))return'ou';if(word.includes('ow'))return'ow';return word.slice(0,2)}
function unoCardHTML(c,i,owner=null){const interactive=owner!==null&&i>=0,playable=interactive&&state.uno.turn===owner&&unoPlayable(c)&&(state.uno.drawnOnly===null||state.uno.drawnOnly===i),label=c.special||c.word,corner=c.special?c.symbol:unoDigraph(c.word);return `<button ${!interactive?'disabled':''} data-owner="${owner}" data-uno-card="${i}" class="word-uno-card ${!interactive?'display-card':''} ${playable?'playable':''} ${c.special?'special':''}" style="--card:${c.color||'#5f267d'}" ${interactive?`onclick="chooseUnoCard(${owner},${i})"`:''} aria-label="${label}"><span class="card-corner">${corner}</span><strong>${label}</strong>${c.special?`<span class="card-art">${c.symbol}</span>`:''}</button>`}
function unoGuideCard(name,symbol,color){return `<span class="word-uno-card display-card special guide-card" style="--card:${color}"><span class="card-corner">${symbol}</span><strong>${name}</strong><span class="card-art">${symbol}</span></span>`}
function unoPanel(type){if(type==='special'){const descriptions={'Skip':'The next player misses a turn.','Reverse':'The play direction changes.','Draw 2':'The next player takes two cards.','Wild':'Choose any color.','Wild Draw 4':'Choose a color. The next player takes four cards.'},guideColors=['#32894a','#2385bd','#c83d2f','#6b2b82','#6b2b82'];return `<div class="uno-info-modal"><div class="special-guide-panel"><h2>Special Cards</h2><p class="guide-intro">Look at the card, then use its magic!</p><div class="special-guide">${unoSpecials.map(([n,s],i)=>`<div class="special-guide-row">${unoGuideCard(n,s,guideColors[i])}<p><b>${n}</b><span>${descriptions[n]}</span></p></div>`).join('')}</div><button onclick="state.uno.panel=null;render()">Close</button></div></div>`}return `<div class="lab-tutorial uno-rules-tutorial"><div><h2>How to Play</h2><div class="uno-rule-cards">${unoGuideCard('owl','OW','#32894a')}<b>→</b>${unoGuideCard('cow','CO','#32894a')}</div><div class="uno-rule-list"><p><b>1.</b> Fox and Owl take turns.</p><p><b>2.</b> Match the color or word.</p><p><b>3.</b> Say the word, then press <b>OK</b>.</p><p><b>4.</b> With one card left, press <b>UNO!</b></p><p><b>5.</b> The first player with no cards wins.</p></div><button onclick="state.uno.panel=null;state.uno.startedAt=Date.now();render()">Let’s Play!</button></div></div>`}
function renderUno(){const u=state.uno;if(u.winner!==null){const owl=u.winner===1;app.innerHTML=shell(`<main class="uno-game-screen"><img class="uno-room-bg" src="assets/uno-room-3d.png?v=1" alt="Magical Fox and Owl card laboratory"><div class="uno-finish"><h1>${owl?'You Win!':'Fox Wins!'}</h1><h2>${owl?'The Owl’s laboratory is safe!':'Try again!'}</h2><p>Time: <b>${formatTime(u.elapsed)}</b> · Cards played: <b>${u.played}</b></p><button onclick="initUno()">Play Again</button></div></main>`,'games');return}const top=u.discard.at(-1),hasPlay=u.players[1].hand.some(unoPlayable);app.innerHTML=shell(`<main class="uno-game-screen"><img class="uno-room-bg" src="assets/uno-room-3d.png?v=1" alt="Magical Fox and Owl card laboratory"><button class="uno-back" onclick="go('home')">← Games</button><h1 class="uno-title">Word Uno: Fox vs Owl</h1><div class="uno-clock"><span id="unoTime">${formatTime(u.elapsed)}</span><b>${u.players[0].hand.length} : ${u.players[1].hand.length}</b></div><aside class="uno-side-tools"><button onclick="state.uno.panel='special';render()"><i>★</i><span>Special Cards</span></button><button onclick="state.uno.panel='rules';render()"><i>?</i><span>Rules</span></button></aside><section class="uno-table"><div class="fox-status"><b>FOX</b><span>${u.players[0].hand.length} cards</span><div class="fox-cards">${u.players[0].hand.slice(0,7).map((c,i)=>unoCardHTML(c,i,true)).join('')}</div></div><div class="uno-piles"><button class="uno-deck" onclick="unoDraw()"><span>OWL</span><small>${u.deck.length}</small></button><div class="uno-discard">${unoCardHTML(top,-1,false)}</div><div class="active-color" style="--active:${u.activeColor}"></div></div><div class="owl-status"><b>OWL</b><span>${u.players[1].hand.length} cards</span></div><p class="uno-reaction">${u.reaction}</p><div class="owl-hand">${u.players[1].hand.map(unoCardHTML).join('')}</div><div class="uno-bottom-actions"><button class="draw-card-btn" onclick="unoDraw()" ${hasPlay||u.turn!==1?'disabled':''}>Draw Card</button><button class="uno-call ${u.unoWindow?'urgent':''}" onclick="pressUno()" ${!u.unoWindow?'disabled':''}>UNO!</button></div></section>${u.pending?`<div class="reading-overlay"><div class="reading-card"><small>READ THE WORD</small><strong>${u.pending.card.word}</strong><button onclick="confirmUnoWord()">OK</button></div></div>`:''}${u.colorChoice?`<div class="uno-color-modal"><div><h2>Choose a color</h2><div>${colors.map(c=>`<button style="--pick:${c}" onclick="chooseWildColor('${c}')"></button>`).join('')}</div></div></div>`:''}${u.panel?unoPanel(u.panel):''}</main>`,'games')}
function renderUno(){const u=state.uno;if(u.winner!==null){const name=u.players[u.winner].name;app.innerHTML=shell(`<main class="uno-game-screen"><img class="uno-room-bg" src="assets/uno-room-3d.png?v=2" alt="Magical Fox and Owl card laboratory"><div class="uno-finish"><h1>${name} Wins!</h1><h2>Wonderful reading!</h2><p>Time: <b>${formatTime(u.elapsed)}</b> · Cards played: <b>${u.played}</b></p><button onclick="initUno()">Play Again</button></div></main>`,'games');return}const top=u.discard.at(-1),current=u.turn,hasPlay=u.players[current].hand.some(unoPlayable),playerPanel=pi=>`<div class="duo-player ${pi===0?'fox-player':'owl-player'} ${u.turn===pi?'current':''}"><h2>${u.players[pi].name}${u.turn===pi?' — Your turn!':''}</h2><span>${u.players[pi].hand.length} cards</span><div class="duo-hand">${u.players[pi].hand.map((c,i)=>unoCardHTML(c,i,pi)).join('')}</div></div>`;app.innerHTML=shell(`<main class="uno-game-screen duo-uno-screen"><img class="uno-room-bg" src="assets/uno-room-3d.png?v=2" alt="Magical Fox and Owl card laboratory"><button class="uno-back" onclick="go('home')">← Games</button><h1 class="uno-title">Word Uno: Fox vs Owl</h1><div class="uno-clock"><span id="unoTime">${formatTime(u.elapsed)}</span><b>${u.players[0].hand.length} : ${u.players[1].hand.length}</b></div><aside class="uno-side-tools"><button onclick="state.uno.panel='special';render()"><i>★</i><span>Special Cards</span></button><button onclick="state.uno.panel='rules';render()"><i>?</i><span>Rules</span></button></aside><section class="uno-table duo-uno-table">${playerPanel(0)}<div class="duo-center"><div class="uno-piles"><button class="uno-deck" onclick="unoDraw()"><span>OWL</span><small>${u.deck.length}</small></button><div class="uno-discard">${unoCardHTML(top,-1,null)}</div><div class="active-color" style="--active:${u.activeColor}"></div></div><p class="uno-reaction">${u.reaction}</p><div class="uno-bottom-actions"><button class="draw-card-btn" onclick="unoDraw()" ${hasPlay?'disabled':''}>${u.players[current].name}: Draw Card</button><button class="uno-call ${u.unoWindow?'urgent':''}" onclick="pressUno()" ${!u.unoWindow?'disabled':''}>UNO!</button></div></div>${playerPanel(1)}</section>${u.pending?`<div class="reading-overlay"><div class="reading-card"><small>${u.players[u.pending.pi].name.toUpperCase()}, READ THE WORD</small><strong>${u.pending.card.word}</strong><button onclick="confirmUnoWord()">OK</button></div></div>`:''}${u.colorChoice?`<div class="uno-color-modal"><div><h2>${u.players[u.colorChoice.pi].name}, choose a color</h2><div>${colors.map(c=>`<button style="--pick:${c}" onclick="chooseWildColor('${c}')"></button>`).join('')}</div></div></div>`:''}${u.panel?unoPanel(u.panel):''}</main>`,'games')}
function initBowling(){const balls=shuffle(bowlWords).map((x,i)=>({word:x[0],base:x[1],special:i===2?'⭐':i===5?'🔁':i===8?'🦊':i===11?'🦉':i===13?'💥':null,used:false,color:colors[(x[1]-1)%4]}));state.bowl={balls,turn:0,scores:[0,0],selected:null,rolling:null,extra:false,done:false}}
function chooseBall(i){const b=state.bowl;if(b.balls[i].used)return;b.selected=i;render()}
function bowlTry(){state.bowl.selected=null;state.bowl.turn=1-state.bowl.turn;render();toast('Try the word again next turn!')}
function bowlCorrect(){const b=state.bowl,ball=b.balls[b.selected];let pts=ball.special==='⭐'?5:ball.special==='💥'?1+Math.floor(Math.random()*5):Math.random()<.12?0:ball.base;ball.used=true;b.selected=null;b.rolling={pts,word:ball.word};b.scores[b.turn]+=pts;b.extra=ball.special==='🔁';render();setTimeout(()=>{b.rolling=null;if(!b.extra)b.turn=1-b.turn;b.extra=false;if(b.balls.every(x=>x.used)){b.done=true;saveStars(15)}render()},1700)}
function renderBowling(){const b=state.bowl;if(b.done){const tie=b.scores[0]===b.scores[1],winner=b.scores[0]>b.scores[1]?'Fox Team':'Owl Team';app.innerHTML=shell(`<main class="screen"><div class="game-shell">${gameHead('Forest Bowling','Final score')}<section class="panel">${endView('🏆',tie?'It’s a tie!':`${winner} wins!`,`Fox Team: ${b.scores[0]} · Owl Team: ${b.scores[1]}`,'Play again','initBowling();render()')}</section></div></main>`,'games');return}app.innerHTML=shell(`<main class="screen"><div class="game-shell">${gameHead('Forest Bowling',`${b.balls.filter(x=>!x.used).length} balls left`)}<section class="panel"><div class="bowling-score"><div class="team-score">🦊 FOX TEAM<br>${b.scores[0]} points</div><div class="turn-pill">${b.turn===0?'🦊 Fox':'🦉 Owl'} Team’s turn</div><div class="team-score owl-team">🦉 OWL TEAM<br>${b.scores[1]} points</div></div><div class="lane"><div class="pins">🎳🎳🎳🎳🎳</div>${b.rolling?`<div class="result-banner">${b.rolling.pts?`Great reading! +${b.rolling.pts}`:'Oops! Gutter ball!'}</div><div class="roll-ball"></div>`:`<p class="instruction">Choose a mystery ball!</p><div class="ball-grid">${b.balls.map((x,i)=>`<button class="ball ${x.used?'used':''}" ${x.used?'disabled':''} onclick="chooseBall(${i})" style="background:${x.color}">${i+1}</button>`).join('')}</div>`}</div></section></div>${b.selected!==null?wordModal(b.balls[b.selected]):''}</main>`,'games')}
function wordModal(ball){return `<div class="modal"><div class="modal-card"><div style="font-size:44px">${ball.special||'🎳'}</div><p class="instruction">Read this word aloud</p><div class="modal-word">${ball.word}</div>${ball.special==='🦉'?`<p>${ball.word.replace(/(ou|ow|ph)/,'·$1·')}</p>`:''}<div class="modal-actions"><button class="primary secondary" onclick="speak('${ball.word}')">🔊 Hint</button><button class="primary try-btn" onclick="bowlTry()">Try again</button><button class="primary correct-btn" onclick="bowlCorrect()">✓ Correct</button></div></div></div>`}
function endView(icon,title,text,button,action){return `<div class="end-card" style="text-align:center"><div class="trophy">${icon}</div><h2 style="font:800 40px 'Baloo 2';margin:4px">${title}</h2><p>${text}</p><button class="primary" onclick="${action}">${button}</button></div>`}
if(location.hash==='#lab')go('lab');else if(location.hash==='#uno')go('uno');else if(location.hash==='#bowling')go('bowling');else render();
