const $ = (s, root=document) => root.querySelector(s);
const app = $('#app');
const wordsLab = [
  ['phone',0],['owl',1],['photo',2],['cow',3],['cloud',4],['house',5],['ring',6],['king',7]
];
const unoWords = ['owl','cow','cloud','house','mouse','loud','crowd','count','proud','sound','around'];
const bowlWords = [
  ['phone',1],['photo',1],['owl',1],['cow',1],['cloud',2],['house',2],['mouse',2],['sound',2],['dolphin',3],['around',3],['elephant',4],['proud',4],['crowd',4],['count',5],['loud',5]
];
const state={sound:true,screen:'home',lab:null,uno:null,bowl:null};
const shuffle=a=>[...a].sort(()=>Math.random()-.5);
function saveStars(n){const v=+localStorage.getItem('forestStars')||0;localStorage.setItem('forestStars',v+n)}
function toast(t){const el=document.createElement('div');el.className='toast';el.textContent=t;document.body.append(el);setTimeout(()=>el.remove(),2100)}
function speak(word){if(!state.sound)return; speechSynthesis.cancel(); const u=new SpeechSynthesisUtterance(word);u.lang='en-US';u.rate=.75;speechSynthesis.speak(u)}
function shell(content,active=''){return `<div class="app"><header class="topbar"><div class="brand"><span class="brand-leaves">🌿</span><span class="brand-text">Forest Friends<small>LEARNING CLUB</small></span></div></header>${content}</div>`}
function go(screen){state.screen=screen;if(screen==='lab')initLab();if(screen==='uno')initUno();if(screen==='bowling')initBowling();render()}
function toggleSound(){state.sound=!state.sound;render()}
function render(){if(state.screen==='home')renderHome();if(state.screen==='lab')renderLab();if(state.screen==='uno')renderUno();if(state.screen==='bowling')renderBowling()}
function renderHome(){app.innerHTML=shell(`<main class="screen home-screen"><img class="scene-bg" src="assets/home-3d.png?v=20260809-10" alt="Fox and Owl magical forest game room"><div class="portal-badges" aria-hidden="true"><img class="portal-badge lab-badge" src="assets/icon-lab-3d.png?v=12"><img class="portal-badge uno-badge" src="assets/icon-uno-3d.png?v=12"><img class="portal-badge bowling-badge" src="assets/icon-bowling-3d.png?v=12"></div><div class="title-plaque"><h1 class="hero-title">Choose Your<br><span>Adventure</span></h1></div><section class="game-grid">
${homeCard('lab','🧪',"The Owl’s Laboratory",'Match each English word to the right picture and brew a magic potion.','#13a980','#9af3dc55','🦉🔬','Play')}
${homeCard('uno','🃏','Word Uno: Fox vs Owl','Match a color, symbol, or sound pattern. Read every word aloud!','#e27019','#ffd77c55','🦊🦉','Start')}
${homeCard('bowling','🎳','Forest Bowling','Choose a mystery ball, read the word, and roll for your team.','#278dcc','#73c9ff55','🦊🎳🦉','Play')}
</section></main>${adventureInfo()}`,'home');if(location.hash==='#adventures')requestAnimationFrame(()=>document.getElementById('adventures')?.scrollIntoView())}
function adventureInfo(){return `<section class="adventures-info" id="adventures"><div class="info-heading"><span>✦</span><div><p>EXPLORE THE GAMES</p><h2>Meet the Adventures</h2></div><span>✦</span></div><div class="info-grid"><article class="info-card lab-info"><div class="info-icon"><img src="assets/icon-lab-3d.png?v=11" alt="Magical potion flask"></div><div><small>WORD & PICTURE GAME</small><h3>The Owl’s Laboratory</h3><p>Read each English word and choose the matching picture. Every correct answer fills a flask and helps Owl brew a magical potion!</p></div><button onclick="go('lab')">Enter the Lab →</button></article><article class="info-card uno-info"><div class="info-icon"><img src="assets/icon-uno-3d.png?v=11" alt="Colorful OWL word cards"></div><div><small>TWO-PLAYER CARD GAME</small><h3>Word Uno: Fox vs Owl</h3><p>Match cards by color, symbol, or sound pattern. Read every word aloud and use special cards to become the forest champion.</p></div><button onclick="go('uno')">Play Word Uno →</button></article><article class="info-card bowl-info"><div class="info-icon"><img src="assets/icon-bowling-3d.png?v=11" alt="Bowling ball and pins"></div><div><small>TEAM READING CHALLENGE</small><h3>Forest Bowling</h3><p>Choose a mystery ball, read the hidden word, and roll for your team. Score points, discover special balls, and win the golden trophy!</p></div><button onclick="go('bowling')">Go Bowling →</button></article></div></section>`}
function homeCard(id,icon,title,desc,accent,glow,chars,action){return `<article class="game-card" style="--accent:${accent};--glow:${glow}"><div class="game-icon">${icon}</div><h2>${title}</h2><p>${desc}</p><div class="characters">${chars}</div><button class="play-btn" onclick="go('${id}')">${title}</button></article>`}
function gameHead(title,badge){return `<div class="game-header"><button class="back-btn" onclick="go('home')">← Games</button><h1>${title}</h1><div class="badge">${badge}</div></div>`}
const labReadingWords=['dolphin','phone','photo','alphabet','phin','phil','elephant'];
const labColors=['#8c3ee8','#28a9f2','#63bf3d'];
let labTimer=null,labAudio=null,labMusicTimer=null;
let lastLabWord='',lastLabLayout='';
function labKey(tubes){return tubes.map(t=>t.join('')).join('|')}
function labGoal(tubes){return tubes.filter(t=>t.length).every(t=>t.length===4&&t.every(c=>c===t[0]))}
function labSolve(tubes){const start=tubes.map(t=>[...t]),queue=[[start,[]]],seen=new Set([labKey(start)]);for(let qi=0;qi<queue.length&&qi<50000;qi++){const [now,path]=queue[qi];if(labGoal(now))return path;for(let a=0;a<4;a++)for(let b=0;b<4;b++){if(a===b||!now[a].length||now[b].length===4||now[b].length&&now[b].at(-1)!==now[a].at(-1))continue;const next=now.map(t=>[...t]);next[b].push(next[a].pop());const key=labKey(next);if(!seen.has(key)){seen.add(key);queue.push([next,[...path,[a,b]]])}}}return null}
function makeLabPuzzle(){for(let tries=0;tries<180;tries++){const pieces=shuffle([0,0,0,0,1,1,1,1,2,2,2,2]),filled=[pieces.slice(0,4),pieces.slice(4,8),pieces.slice(8,12)],tubes=shuffle([...filled,[]]),key=labKey(tubes),solution=labSolve(tubes);if(key!==lastLabLayout&&solution&&solution.length>=7&&solution.length<=16&&!filled.some(t=>t.every(c=>c===t[0]))){lastLabLayout=key;return tubes}}const fallback=shuffle([[[0,0,1,1],[1,1,2,2],[2,2,0,0],[]],[[0,1,0,1],[1,2,1,2],[2,0,2,0],[]]]);for(const tubes of fallback){const mixed=shuffle(tubes.map(t=>[...t]));if(labSolve(mixed)){lastLabLayout=labKey(mixed);return mixed}}return [[0,0,1,1],[1,1,2,2],[2,2,0,0],[]]}
function nextLabWord(){const choices=labReadingWords.filter(w=>w!==lastLabWord);lastLabWord=choices[Math.floor(Math.random()*choices.length)];return lastLabWord}
function initLab(){state.lab={tubes:makeLabPuzzle(),selected:null,pending:null,word:'',moves:0,history:[],hintsUsed:0,hintPair:null,startedAt:Date.now(),elapsed:0,tutorial:true,won:false,pouring:null};clearInterval(labTimer);labTimer=setInterval(updateLabClock,1000)}
function updateLabClock(){const l=state.lab;if(!l||l.won)return;l.elapsed=Math.floor((Date.now()-l.startedAt)/1000);const e=$('#labTime');if(e)e.textContent=formatTime(l.elapsed)}
function formatTime(s){return `${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}
function validLabMove(from,to){const a=state.lab.tubes[from],b=state.lab.tubes[to];return from!==to&&a.length&&b.length<4&&(!b.length||b.at(-1)===a.at(-1))}
function labAmount(){return 1}
function labFlaskTap(i){const l=state.lab;if(l.pending||l.pouring||l.won)return;if(l.selected===null){if(!l.tubes[i].length)return labShake(i);l.selected=i;l.hintPair=null;playLabTone(420,.08);return renderLab()}if(l.selected===i){l.selected=null;return renderLab()}const from=l.selected;if(!validLabMove(from,i)){renderLab();return setTimeout(()=>labShake(i),20)}l.selected=null;l.pending={from,to:i};l.word=nextLabWord();playLabTone(650,.12);renderLab()}
function labShake(i){document.querySelector(`[data-flask="${i}"]`)?.classList.add('invalid');setTimeout(()=>document.querySelector(`[data-flask="${i}"]`)?.classList.remove('invalid'),450)}
function confirmLabWord(){const l=state.lab;if(!l.pending)return;const {from,to}=l.pending,amount=labAmount(from,to);l.history.push(l.tubes.map(t=>[...t]));l.pouring={from,to};l.pending=null;l.moves++;renderLab();setTimeout(()=>{for(let n=0;n<amount;n++)l.tubes[to].push(l.tubes[from].pop());l.pouring=null;playLabTone(760,.18);l.won=labSolved();if(l.won){l.elapsed=Math.floor((Date.now()-l.startedAt)/1000);clearInterval(labTimer);saveStars(10);playLabWin()}renderLab()},650)}
function labSolved(){return state.lab.tubes.filter(t=>t.length).every(t=>t.length===4&&t.every(c=>c===t[0]))}
function undoLab(){const l=state.lab;if(!l.history.length||l.pouring)return;l.tubes=l.history.pop();l.moves=Math.max(0,l.moves-1);l.selected=null;l.hintPair=null;renderLab()}
function restartLab(){initLab();state.lab.tutorial=false;renderLab()}
function hintLab(){const l=state.lab;if(l.hintsUsed>=3||l.pending||l.pouring)return;const move=labSolve(l.tubes)?.[0];if(move){l.hintPair=move;l.hintsUsed++;renderLab()}}
function closeLabTutorial(){state.lab.tutorial=false;state.lab.startedAt=Date.now();playLabTone(520,.12);startLabMusic();renderLab()}
function startLabMusic(){clearInterval(labMusicTimer);if(!state.sound)return;const notes=[220,262,294,262];let i=0;labMusicTimer=setInterval(()=>{if(state.screen==='lab'&&state.sound)playLabTone(notes[i++%notes.length],1.8)},4200)}
function playLabTone(freq,d=.1){if(!state.sound)return;try{labAudio=labAudio||new AudioContext();const o=labAudio.createOscillator(),g=labAudio.createGain();o.frequency.value=freq;o.type='sine';g.gain.setValueAtTime(.07,labAudio.currentTime);g.gain.exponentialRampToValueAtTime(.001,labAudio.currentTime+d);o.connect(g).connect(labAudio.destination);o.start();o.stop(labAudio.currentTime+d)}catch{}}
function playLabWin(){[523,659,784,1046].forEach((n,i)=>setTimeout(()=>playLabTone(n,.35),i*160))}
function labTubeHtml(t,i){const l=state.lab,canReceive=l.selected!==null&&validLabMove(l.selected,i),hintFrom=l.hintPair?.[0]===i,hintTo=l.hintPair?.[1]===i;return `<button class="sort-flask ${l.selected===i?'selected':''} ${canReceive?'can-receive':''} ${hintFrom?'hint-from':''} ${hintTo?'hint-to':''} ${l.pouring?.from===i?'pouring':''}" data-flask="${i}" onclick="labFlaskTap(${i})" aria-label="Flask ${i+1}"><span class="flask-neck"></span><span class="liquid-stack">${t.map((c,j)=>`<i style="--c:${labColors[c]};--layer:${j}"></i>`).join('')}</span></button>`}
function renderLab(){const l=state.lab;const game=l.won?`<div class="water-win"><div class="win-potion"></div><h2>You Win!</h2><h3>Great job!</h3><p>Moves: <b>${l.moves}</b> &nbsp; Time: <b>${formatTime(l.elapsed)}</b></p><button onclick="restartLab()">Play Again</button></div>`:`<div class="water-game"><p class="sort-goal">Sort the potions by color!</p><div class="sort-flasks">${l.tubes.map(labTubeHtml).join('')}</div><p class="sort-help">Tap a flask, then tap another flask.</p></div>`;const reading=l.pending?`<div class="reading-overlay"><div class="reading-card"><small>READ THE MAGIC WORD</small><strong>${l.word}</strong><button onclick="confirmLabWord()">OK</button></div></div>`:'';const tutorial=l.tutorial?`<div class="lab-tutorial"><div><h2>Sort the colors!</h2><div class="tutorial-flasks"><i></i><b>→</b><i></i></div><p>Tap a flask, then tap another flask.</p><p>Read the word and tap <b>OK</b> to pour.</p><button onclick="closeLabTutorial()">Let’s Play!</button></div></div>`:'';app.innerHTML=shell(`<main class="lab-game-screen water-sort-screen"><img class="lab-room-bg" src="assets/lab-room-3d.png?v=20260809-14" alt="Cozy magical owl laboratory"><button class="lab-back" onclick="go('home')">← Games</button><h1 class="lab-title">The Owl’s Laboratory</h1><div class="lab-hud"><span>Moves <b>${l.moves}</b></span><span>Time <b id="labTime">${formatTime(l.elapsed)}</b></span><span>Hints <b>${l.hintsUsed}/3</b></span></div><section class="lab-board-ui water-board">${game}</section><nav class="lab-controls"><button onclick="undoLab()" ${!l.history.length?'disabled':''}>↶ <span>Undo</span></button><button onclick="restartLab()">↻ <span>Restart</span></button><button onclick="hintLab()" ${l.hintsUsed>=3?'disabled':''}>? <span>Hint</span></button></nav>${reading}${tutorial}</main>`,'games')}
const colors=['#e85454','#2fa66d','#358fd1','#e7a52b'];
function makeCard(word,i){let special=null;if(i===2)special='Skip';if(i===5)special='Reverse';if(i===8)special='Draw Two';if(i===10)special='Magic Word';return{word,special,color:colors[i%4],symbol:word.includes('ou')?'OU':'OW'}}
function initUno(){const deck=shuffle(unoWords.map(makeCard));state.uno={players:[{name:'Fox',icon:'🦊',hand:deck.slice(0,5)},{name:'Owl',icon:'🦉',hand:deck.slice(5,10)}],deck:deck.slice(10),discard:[makeCard('owl',1)],turn:0,direction:1,winner:null,chosen:null};refillUno()}
function refillUno(){const u=state.uno;while(u.players[0].hand.length<7)u.players[0].hand.push(makeCard(unoWords[Math.floor(Math.random()*unoWords.length)],Math.floor(Math.random()*11)));while(u.players[1].hand.length<7)u.players[1].hand.push(makeCard(unoWords[Math.floor(Math.random()*unoWords.length)],Math.floor(Math.random()*11)))}
function unoPlayable(c,top){return c.color===top.color||c.symbol===top.symbol||c.special==='Magic Word'||c.word===top.word}
function unoPlay(pi,ci){const u=state.uno;if(pi!==u.turn)return toast('Wait for your turn!');const card=u.players[pi].hand[ci],top=u.discard.at(-1);if(!unoPlayable(card,top))return toast('Match color, symbol, or category');speak(card.word);u.players[pi].hand.splice(ci,1);u.discard.push(card);if(!u.players[pi].hand.length){u.winner=pi;saveStars(12);return render()}let next=(u.turn+u.direction+2)%2;if(card.special==='Reverse'||card.special==='Skip')next=u.turn;if(card.special==='Draw Two'){u.players[next].hand.push(makeCard(unoWords[Math.floor(Math.random()*11)],3),makeCard(unoWords[Math.floor(Math.random()*11)],6))}u.turn=next;render()}
function unoDraw(){const u=state.uno;u.players[u.turn].hand.push(makeCard(unoWords[Math.floor(Math.random()*11)],Math.floor(Math.random()*11)));u.turn=1-u.turn;render()}
function renderUno(){const u=state.uno;if(u.winner!==null){app.innerHTML=shell(`<main class="screen"><div class="game-shell">${gameHead('Word Uno','🏆 Winner')}<section class="panel">${endView('🎁',`${u.players[u.winner].name} wins!`,'You earned a magic forest key.','Play again','initUno();render()')}</section></div></main>`,'games');return}const top=u.discard.at(-1);const player=(p,i)=>`<div class="player ${u.turn===i?'current':''}"><div class="avatar">${p.icon}</div><h2>${p.name} ${u.turn===i?'— Your turn!':''}</h2><div class="hand">${p.hand.map((c,j)=>`<button aria-label="${c.word}" onclick="unoPlay(${i},${j})" class="mini-card" style="background:${c.color};--rot:${(j%3-1)*4}deg">${c.special?c.special:c.word}</button>`).join('')}</div></div>`;app.innerHTML=shell(`<main class="screen"><div class="game-shell">${gameHead('Word Uno: Fox vs Owl',`${u.players[0].hand.length} : ${u.players[1].hand.length}`)}<section class="panel"><p class="instruction">Put down a matching card and read the word aloud.</p><div class="uno-board">${player(u.players[0],0)}<div class="uno-center"><div class="uno-card" style="background:${top.color}"><span class="symbol">${top.special?'✨':top.symbol}</span><span class="word">${top.special||top.word}</span></div><div class="uno-actions"><button class="secondary" onclick="speak('${top.word}')">🔊 Read word</button><button class="secondary" onclick="unoDraw()">＋ Draw card</button></div></div>${player(u.players[1],1)}</div></section></div></main>`,'games')}
function initBowling(){const balls=shuffle(bowlWords).map((x,i)=>({word:x[0],base:x[1],special:i===2?'⭐':i===5?'🔁':i===8?'🦊':i===11?'🦉':i===13?'💥':null,used:false,color:colors[(x[1]-1)%4]}));state.bowl={balls,turn:0,scores:[0,0],selected:null,rolling:null,extra:false,done:false}}
function chooseBall(i){const b=state.bowl;if(b.balls[i].used)return;b.selected=i;render()}
function bowlTry(){state.bowl.selected=null;state.bowl.turn=1-state.bowl.turn;render();toast('Try the word again next turn!')}
function bowlCorrect(){const b=state.bowl,ball=b.balls[b.selected];let pts=ball.special==='⭐'?5:ball.special==='💥'?1+Math.floor(Math.random()*5):Math.random()<.12?0:ball.base;ball.used=true;b.selected=null;b.rolling={pts,word:ball.word};b.scores[b.turn]+=pts;b.extra=ball.special==='🔁';render();setTimeout(()=>{b.rolling=null;if(!b.extra)b.turn=1-b.turn;b.extra=false;if(b.balls.every(x=>x.used)){b.done=true;saveStars(15)}render()},1700)}
function renderBowling(){const b=state.bowl;if(b.done){const tie=b.scores[0]===b.scores[1],winner=b.scores[0]>b.scores[1]?'Fox Team':'Owl Team';app.innerHTML=shell(`<main class="screen"><div class="game-shell">${gameHead('Forest Bowling','Final score')}<section class="panel">${endView('🏆',tie?'It’s a tie!':`${winner} wins!`,`Fox Team: ${b.scores[0]} · Owl Team: ${b.scores[1]}`,'Play again','initBowling();render()')}</section></div></main>`,'games');return}app.innerHTML=shell(`<main class="screen"><div class="game-shell">${gameHead('Forest Bowling',`${b.balls.filter(x=>!x.used).length} balls left`)}<section class="panel"><div class="bowling-score"><div class="team-score">🦊 FOX TEAM<br>${b.scores[0]} points</div><div class="turn-pill">${b.turn===0?'🦊 Fox':'🦉 Owl'} Team’s turn</div><div class="team-score owl-team">🦉 OWL TEAM<br>${b.scores[1]} points</div></div><div class="lane"><div class="pins">🎳🎳🎳🎳🎳</div>${b.rolling?`<div class="result-banner">${b.rolling.pts?`Great reading! +${b.rolling.pts}`:'Oops! Gutter ball!'}</div><div class="roll-ball"></div>`:`<p class="instruction">Choose a mystery ball!</p><div class="ball-grid">${b.balls.map((x,i)=>`<button class="ball ${x.used?'used':''}" ${x.used?'disabled':''} onclick="chooseBall(${i})" style="background:${x.color}">${i+1}</button>`).join('')}</div>`}</div></section></div>${b.selected!==null?wordModal(b.balls[b.selected]):''}</main>`,'games')}
function wordModal(ball){return `<div class="modal"><div class="modal-card"><div style="font-size:44px">${ball.special||'🎳'}</div><p class="instruction">Read this word aloud</p><div class="modal-word">${ball.word}</div>${ball.special==='🦉'?`<p>${ball.word.replace(/(ou|ow|ph)/,'·$1·')}</p>`:''}<div class="modal-actions"><button class="primary secondary" onclick="speak('${ball.word}')">🔊 Hint</button><button class="primary try-btn" onclick="bowlTry()">Try again</button><button class="primary correct-btn" onclick="bowlCorrect()">✓ Correct</button></div></div></div>`}
function endView(icon,title,text,button,action){return `<div class="end-card" style="text-align:center"><div class="trophy">${icon}</div><h2 style="font:800 40px 'Baloo 2';margin:4px">${title}</h2><p>${text}</p><button class="primary" onclick="${action}">${button}</button></div>`}
if(location.hash==='#lab')go('lab');else render();
