const $ = (s, root=document) => root.querySelector(s);
const app = $('#app');
const wordsLab = [
  ['phone','📱'],['owl','🦉'],['photo','🖼️'],['cow','🐄'],['cloud','☁️'],['house','🏠'],['ring','💍'],['king','🤴']
];
const unoWords = ['owl','cow','cloud','house','mouse','loud','crowd','count','proud','sound','around'];
const bowlWords = [
  ['phone',1],['photo',1],['owl',1],['cow',1],['cloud',2],['house',2],['mouse',2],['sound',2],['dolphin',3],['around',3],['elephant',4],['proud',4],['crowd',4],['count',5],['loud',5]
];
const state={sound:true,screen:'home',lab:null,uno:null,bowl:null};
const shuffle=a=>[...a].sort(()=>Math.random()-.5);
function saveStars(n){const v=+localStorage.getItem('forestStars')||0;localStorage.setItem('forestStars',v+n)}
function toast(t){const el=document.createElement('div');el.className='toast';el.textContent=t;document.body.append(el);setTimeout(()=>el.remove(),2100)}
function speak(word){if(!state.sound)return; speechSynthesis.cancel(); const u=new SpeechSynthesisUtterance(word);u.lang='en-US';u.rate=.75;speechSynthesis.speak(u)}
function shell(content,active=''){return `<div class="app"><header class="topbar"><div class="brand"><span class="brand-leaves">🌿</span><span class="brand-text">Forest Friends<small>LEARNING CLUB</small></span></div><nav class="nav-actions"><button class="nav-btn ${active==='home'?'active':''}" onclick="go('home')">🏠 <span>Home</span></button><button class="nav-btn ${active==='games'?'active':''}" onclick="go('home')">🎮 <span>Games</span></button><button class="nav-btn nav-extra">⭐ <span>Achievements</span></button><button class="nav-btn nav-extra">📖 <span>Library</span></button></nav><div class="profile"><span class="profile-face">🦊</span><span><b>Hello, Explorer!</b><small>⭐ ${localStorage.getItem('forestStars')||120}</small></span><button class="sound-btn" onclick="toggleSound()">${state.sound?'🔊':'🔇'}</button></div></header>${content}</div>`}
function go(screen){state.screen=screen;if(screen==='lab')initLab();if(screen==='uno')initUno();if(screen==='bowling')initBowling();render()}
function toggleSound(){state.sound=!state.sound;render()}
function render(){if(state.screen==='home')renderHome();if(state.screen==='lab')renderLab();if(state.screen==='uno')renderUno();if(state.screen==='bowling')renderBowling()}
function renderHome(){app.innerHTML=shell(`<main class="screen home-screen"><img class="scene-bg" src="assets/home-3d.png?v=20260809-5" alt="Fox and Owl magical forest game room"><div class="title-plaque"><h1 class="hero-title">Choose Your<br><span>Adventure</span></h1></div><section class="game-grid">
${homeCard('lab','🧪',"The Owl’s Laboratory",'Match each English word to the right picture and brew a magic potion.','#13a980','#9af3dc55','🦉🔬','Play')}
${homeCard('uno','🃏','Word Uno: Fox vs Owl','Match a color, symbol, or sound pattern. Read every word aloud!','#e27019','#ffd77c55','🦊🦉','Start')}
${homeCard('bowling','🎳','Forest Bowling','Choose a mystery ball, read the word, and roll for your team.','#278dcc','#73c9ff55','🦊🎳🦉','Play')}
</section><div class="pick-sign">Pick a game<br><small>and start fun!</small></div><div class="sparkles">✦　·　✧　·　✦　·　✧</div></main>`,'home')}
function homeCard(id,icon,title,desc,accent,glow,chars,action){return `<article class="game-card" style="--accent:${accent};--glow:${glow}"><div class="game-icon">${icon}</div><h2>${title}</h2><p>${desc}</p><div class="characters">${chars}</div><button class="play-btn" onclick="go('${id}')">▶ ${action}</button></article>`}
function gameHead(title,badge){return `<div class="game-header"><button class="back-btn" onclick="go('home')">← Games</button><h1>${title}</h1><div class="badge">${badge}</div></div>`}
function initLab(){state.lab={index:0,errors:0,filled:0,options:[],smoke:false,done:false};setLabOptions()}
function setLabOptions(){const l=state.lab, correct=wordsLab[l.index];l.options=shuffle([correct,...shuffle(wordsLab.filter(x=>x[0]!==correct[0])).slice(0,3)])}
function labPick(word,btn){const l=state.lab,correct=wordsLab[l.index][0];if(word===correct){btn.classList.add('correct');l.filled++;speak(correct);setTimeout(()=>{l.index++;if(l.index>=wordsLab.length){l.done=true;saveStars(10)}else setLabOptions();render()},550)}else{btn.classList.add('wrong');l.errors++;if(l.errors>=3){l.smoke=true;setTimeout(()=>{l.smoke=false;l.errors=0;render()},1100)}else setTimeout(()=>btn.classList.remove('wrong'),500);renderLabStatus()}}
function renderLabStatus(){const el=$('#labStatus');if(el)el.textContent=`Mistakes: ${state.lab.errors}/3`}
function renderLab(){const l=state.lab;let body;if(l.done)body=endView('🚪✨','The magic door is open!','Wonderful reading! Your potion is ready.','Play again','initLab();render()');else body=`<div class="lab-layout"><div class="owl-scene">${l.smoke?'<div class="smoke">💨🤪💨</div>':'<div class="owl">🦉</div>'}<div class="flasks">${[0,1,2,3].map((_,i)=>`<div class="flask ${l.filled>i?'done':''}" style="--fill:${Math.min(100,Math.max(0,(l.filled-i*2)*50))}%;--liquid:${['#ef5c70','#44cbe3','#8c62de','#52c878'][i]}"></div>`).join('')}</div></div><div><div class="word-card"><div class="big-word">${wordsLab[l.index][0]}</div><button class="secondary" onclick="speak('${wordsLab[l.index][0]}')">🔊 Hear word</button></div><div class="picture-grid">${l.options.map(o=>`<button class="picture-option" onclick="labPick('${o[0]}',this)">${o[1]}<span>Choose picture</span></button>`).join('')}</div></div></div>`;app.innerHTML=shell(`<main class="screen"><div class="game-shell">${gameHead("The Owl’s Laboratory",`<span id="labStatus">Mistakes: ${l.errors}/3</span>`)}<section class="panel"><p class="instruction">Read the word and choose the matching picture.</p><div class="progress"><span style="width:${l.index/wordsLab.length*100}%"></span></div>${body}</section></div></main>`,'games')}
const colors=['#e85454','#2fa66d','#358fd1','#e7a52b'];
function makeCard(word,i){let special=null;if(i===2)special='Skip';if(i===5)special='Reverse';if(i===8)special='Draw Two';if(i===10)special='Magic Word';return{word,special,color:colors[i%4],symbol:word.includes('ou')?'OU':'OW'}}
function initUno(){const deck=shuffle(unoWords.map(makeCard));state.uno={players:[{name:'Fox',icon:'🦊',hand:deck.slice(0,5)},{name:'Owl',icon:'🦉',hand:deck.slice(5,10)}],deck:deck.slice(10),discard:[makeCard('owl',1)],turn:0,direction:1,winner:null,chosen:null};refillUno()}
function refillUno(){const u=state.uno;while(u.players[0].hand.length<7)u.players[0].hand.push(makeCard(unoWords[Math.floor(Math.random()*unoWords.length)],Math.floor(Math.random()*11)));while(u.players[1].hand.length<7)u.players[1].hand.push(makeCard(unoWords[Math.floor(Math.random()*unoWords.length)],Math.floor(Math.random()*11)))}
function unoPlayable(c,top){return c.color===top.color||c.symbol===top.symbol||c.special==='Magic Word'||c.word===top.word}
function unoPlay(pi,ci){const u=state.uno;if(pi!==u.turn)return toast('Wait for your turn!');const card=u.players[pi].hand[ci],top=u.discard.at(-1);if(!unoPlayable(card,top))return toast('Match color, symbol, or category');speak(card.word);u.players[pi].hand.splice(ci,1);u.discard.push(card);if(!u.players[pi].hand.length){u.winner=pi;saveStars(12);return render()}let next=(u.turn+u.direction+2)%2;if(card.special==='Reverse'||card.special==='Skip')next=u.turn;if(card.special==='Draw Two'){u.players[next].hand.push(makeCard(unoWords[Math.floor(Math.random()*11)],3),makeCard(unoWords[Math.floor(Math.random()*11)],6))}u.turn=next;render()}
function unoDraw(){const u=state.uno;u.players[u.turn].hand.push(makeCard(unoWords[Math.floor(Math.random()*11)],Math.floor(Math.random()*11)));u.turn=1-u.turn;render()}
function renderUno(){const u=state.uno;if(u.winner!==null){app.innerHTML=shell(`<main class="screen"><div class="game-shell">${gameHead('Word Uno','🏆 Winner')}<section class="panel">${endView('🎁',`${u.players[u.winner].name} wins!`,'You earned a magic forest key.','Play again','initUno();render()')}</section></div></main>`,'games');return}const top=u.discard.at(-1);const player=(p,i)=>`<div class="player ${u.turn===i?'current':''}"><div class="avatar">${p.icon}</div><h2>${p.name} ${u.turn===i?'— Your turn!':''}</h2><div class="hand">${p.hand.map((c,j)=>`<button aria-label="${c.word}" onclick="unoPlay(${i},${j})" class="mini-card" style="background:${c.color};--rot:${(j%3-1)*4}deg">${c.special?c.special:c.word}</button>`).join('')}</div></div>`;app.innerHTML=shell(`<main class="screen"><div class="game-shell">${gameHead('Word Uno: Fox vs Owl',`${u.players[0].hand.length} : ${u.players[1].hand.length}`)}<section class="panel"><p class="instruction">Put down a matching card and read the word aloud.</p><div class="uno-board">${player(u.players[0],0)}<div class="uno-center"><div class="uno-card" style="background:${top.color}"><span class="symbol">${top.special?'✨':top.symbol}</span><span class="word">${top.special||top.word}</span></div><div class="uno-actions"><button class="secondary" onclick="speak('${top.word}')">🔊 Read word</button><button class="secondary" onclick="unoDraw()">＋ Draw card</button></div></div>${player(u.players[1],1)}</div></section></div></main>`,'games')}
function initBowling(){const balls=shuffle(bowlWords).map((x,i)=>({word:x[0],base:x[1],special:i===2?'⭐':i===5?'🔁':i===8?'🦊':i===11?'🦉':i===13?'💥':null,used:false,color:colors[(x[1]-1)%4]}));state.bowl={balls,turn:0,scores:[0,0],selected:null,rolling:null,extra:false,done:false}}
function chooseBall(i){const b=state.bowl;if(b.balls[i].used)return;b.selected=i;render()}
function bowlTry(){state.bowl.selected=null;state.bowl.turn=1-state.bowl.turn;render();toast('Try the word again next turn!')}
function bowlCorrect(){const b=state.bowl,ball=b.balls[b.selected];let pts=ball.special==='⭐'?5:ball.special==='💥'?1+Math.floor(Math.random()*5):Math.random()<.12?0:ball.base;ball.used=true;b.selected=null;b.rolling={pts,word:ball.word};b.scores[b.turn]+=pts;b.extra=ball.special==='🔁';render();setTimeout(()=>{b.rolling=null;if(!b.extra)b.turn=1-b.turn;b.extra=false;if(b.balls.every(x=>x.used)){b.done=true;saveStars(15)}render()},1700)}
function renderBowling(){const b=state.bowl;if(b.done){const tie=b.scores[0]===b.scores[1],winner=b.scores[0]>b.scores[1]?'Fox Team':'Owl Team';app.innerHTML=shell(`<main class="screen"><div class="game-shell">${gameHead('Forest Bowling','Final score')}<section class="panel">${endView('🏆',tie?'It’s a tie!':`${winner} wins!`,`Fox Team: ${b.scores[0]} · Owl Team: ${b.scores[1]}`,'Play again','initBowling();render()')}</section></div></main>`,'games');return}app.innerHTML=shell(`<main class="screen"><div class="game-shell">${gameHead('Forest Bowling',`${b.balls.filter(x=>!x.used).length} balls left`)}<section class="panel"><div class="bowling-score"><div class="team-score">🦊 FOX TEAM<br>${b.scores[0]} points</div><div class="turn-pill">${b.turn===0?'🦊 Fox':'🦉 Owl'} Team’s turn</div><div class="team-score owl-team">🦉 OWL TEAM<br>${b.scores[1]} points</div></div><div class="lane"><div class="pins">🎳🎳🎳🎳🎳</div>${b.rolling?`<div class="result-banner">${b.rolling.pts?`Great reading! +${b.rolling.pts}`:'Oops! Gutter ball!'}</div><div class="roll-ball"></div>`:`<p class="instruction">Choose a mystery ball!</p><div class="ball-grid">${b.balls.map((x,i)=>`<button class="ball ${x.used?'used':''}" ${x.used?'disabled':''} onclick="chooseBall(${i})" style="background:${x.color}">${i+1}</button>`).join('')}</div>`}</div></section></div>${b.selected!==null?wordModal(b.balls[b.selected]):''}</main>`,'games')}
function wordModal(ball){return `<div class="modal"><div class="modal-card"><div style="font-size:44px">${ball.special||'🎳'}</div><p class="instruction">Read this word aloud</p><div class="modal-word">${ball.word}</div>${ball.special==='🦉'?`<p>${ball.word.replace(/(ou|ow|ph)/,'·$1·')}</p>`:''}<div class="modal-actions"><button class="primary secondary" onclick="speak('${ball.word}')">🔊 Hint</button><button class="primary try-btn" onclick="bowlTry()">Try again</button><button class="primary correct-btn" onclick="bowlCorrect()">✓ Correct</button></div></div></div>`}
function endView(icon,title,text,button,action){return `<div class="end-card" style="text-align:center"><div class="trophy">${icon}</div><h2 style="font:800 40px 'Baloo 2';margin:4px">${title}</h2><p>${text}</p><button class="primary" onclick="${action}">${button}</button></div>`}
render();
